<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Payments extends Model
{
    protected $fillable=[
        'phone_no',
        'sender_first_name',
        'sender_middle_name',
        'sender_last_name',
        'transaction_id',
        'amount',
        'business_number',
        'acc_no',
        'transaction_type',
        'transaction_time',
        'user_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($model){
            $model->user_id=Auth::id();
            $model->transaction_time=Carbon::now()->timestamp;
        });

        self::created(function($model){
//            $model
        });
    }



    protected $casts=[
        'created_at'=>'date:d M Y',
        'updated_at'=>'date:d M Y'
    ];
}
